<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Files</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>3c6a02ce-f357-4b7d-a403-09647c461139</testSuiteGuid>
   <testCaseLink>
      <guid>2442463e-d989-41d6-9c88-58119e844e51</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PreReq/Pre-Req-Script-FileOps</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee8c6b5b-4cd6-4f2f-a3ea-9d5457cde594</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e02443f-7bc7-4a60-a9ca-7dea0ebfdc7e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
