<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>JS</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>f0773a18-35a4-4b6f-a3bd-441a73d8551f</testSuiteGuid>
   <testCaseLink>
      <guid>2c07d0e3-a5ca-46d0-bc86-b2e423244a4e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PreReq/Pre-Req-Script-JObSubmission</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a77238d6-95dd-4d45-a885-f2c3fbb097d0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddf28354-bcd5-40b0-b7a7-b731ff0fae86</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
