<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>GenericTestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>c0b3d89d-ec76-43b1-b9a6-1bce73d8cdc7</testSuiteGuid>
   <testCaseLink>
      <guid>69c07e6c-ab8b-4590-9680-a4b370aab2f5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2019.3/AltairAccesslogo_JobsTab</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>015be0ef-4498-4dcd-9c0f-8644f8b7aebe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee1669e4-484d-446c-a6cd-6805d5cfa8fd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4d61e8eb-0a4d-4847-82bb-43257c924a45</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2019.3/AltairAccesslogo_persistence_enabled</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1406ec96-79e0-4b8e-9e0a-c6f005913db9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b202ae71-0857-44de-9356-b93a0108d5d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ceffe5f-429f-4fad-9a85-dbc97f464ae4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5f834fb-cf76-40db-bca7-dcc837f9a231</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54155f37-5961-4d10-b956-cb93dea53980</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28e3def8-c697-42b6-a461-703a3f0203cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>941caf00-d842-4fa1-8329-849ce930dd1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3adf954-78f5-4ea9-9adf-efc7c79aa326</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>36f51e78-373a-418e-b670-30a61cf78421</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2019.3/Bookmark_JobSubmissionForm</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>342bf84f-d731-46b2-bc09-0598f54f2c06</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e957165-146e-463b-a224-778888e896fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98ebd070-a82f-4332-81d4-243dafc56d70</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0fd68ee-be16-489f-b4f8-96a8f6773260</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d176fffb-2637-4b0d-99e5-8010ae6b4d00</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9fa49202-fee8-4fed-9fdb-0c148898ec2f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2019.3/ProcessWith_Optistruct</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ecebbc7d-c682-48a7-ae90-b89b965c63d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee159a2f-337e-4f8f-84d6-4c5206a6e4f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13bb1d38-b7f1-4761-8678-46a35eed5c08</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
