<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Generic_Actions</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>bd9aa71a-9cfe-4a43-a3ec-ad03df36fcf5</testSuiteGuid>
   <testCaseLink>
      <guid>75477093-96e5-4a49-b2fb-0f6cd2f77ce4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Generic_Actions/Generic_Actions</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>945c8af2-6545-41da-b312-5e26d56e9660</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestDataForGeneric_Actions</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>945c8af2-6545-41da-b312-5e26d56e9660</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>e47b77ef-b2e7-4db0-8e59-d0281e610867</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>945c8af2-6545-41da-b312-5e26d56e9660</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>af386d66-71c7-4cf3-9748-0abd139a3e50</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
