<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>pre-req</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>52daa727-edaa-4268-8baa-aee9f8384429</testSuiteGuid>
   <testCaseLink>
      <guid>fd495cb4-83b0-4094-adfd-cb267e9613df</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/PreReq/Pre-Req-Script-FileOps</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee8c6b5b-4cd6-4f2f-a3ea-9d5457cde594</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e02443f-7bc7-4a60-a9ca-7dea0ebfdc7e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b4c0c071-1ec8-46de-a969-f672bef13353</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/PreReq/old-Pre-Req-Script-For-FileOps</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18e5855e-a232-4016-9b62-a42bc4ed92d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1866245-a8d8-4227-adfb-19dbefaaafb8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9aaa38c1-3487-44bf-89d0-85ef1f31bf98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cca7cadf-8761-4f59-8947-8c4e626de057</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e855541e-7d9c-4a91-bbe7-8934ae2d4128</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6bd06f69-adb7-468a-9b23-7673d67147fe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/PreReq/old-Pre-Req-Script-For-FolderOps</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8e3e7690-65ca-4925-90cb-6e879f330b54</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6880c36e-506e-48f8-b2c2-94a06e4f4998</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da8d6343-6509-4322-8e34-b6ba793c24fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>333e1ebe-df87-4e15-b618-aa5b9dd6d0dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11f0524e-4616-4edb-a899-16031097033c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ea7aa675-564e-464b-881c-bb05d5c62351</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/PreReq/Pre-Req-Script-For-JobMonitoring</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07e6f513-a04f-4fe3-b70a-198f3f69be18</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64007784-bca4-488a-8a51-9d250067468a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1c87bd78-81b1-402b-ae17-375332c5d79c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e1d0a01-35b1-4e4d-b5c8-bb176ad9c1bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f94f9b9-3a18-4eca-b080-5ff2e6edd9b9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>41701c11-a77e-43f2-acf8-ad1ae325b730</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/PreReq/old-Pre-Req-Script-For-JobSubmission</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e8aad25-1d99-4379-8210-3b7d88bd03b1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6158ddd4-6f7d-4983-873f-6c167915cd28</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3cb4ecf-deea-473d-ab7f-88fe768d1709</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c7d5c30-576c-4557-9ef7-d580c546a40c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb5e92ab-73b3-49a0-b744-ff72ea4203fe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5f0d21df-750a-4ce5-b401-bdcda4747606</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/PreReq/Pre-Req-Script-For-Profiles</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5e91b7d7-7df2-4077-95ee-936d61d69f6f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21d284ab-4779-401a-af91-2c9c796d8744</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>abed14a1-632c-4271-83a5-40182be8ea2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa6db84f-eac4-4a1e-8437-ddfb1a7454c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e35f4df-c494-49c6-8777-66810b0b1f04</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
