<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dateselector</name>
   <tag></tag>
   <elementGuidId>565c08bc-a3e5-462d-9bca-f68e2c4348fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'react-grid-Canvas')]//div//div[1]//div[1]//div[2]//div[1]//div[1]//div[1]//span[1]//div[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
