<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Icon_BookMark</name>
   <tag></tag>
   <elementGuidId>aa4fc169-2457-4c61-ac7e-a3aa39570ff4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>v//div[@id='bookMarkIcon']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'bookMarkIcon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bookMarkIcon</value>
   </webElementProperties>
</WebElementEntity>
