<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_column</name>
   <tag></tag>
   <elementGuidId>e539d6ae-4f59-4b2c-b321-d7f07109d199</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[@id = 'file_col_filter_fileExt' and @class = 'tickmark']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='file_col_filter_fileExt']//span[@class='tickmark']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>file_col_filter_fileExt</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tickmark</value>
   </webElementProperties>
</WebElementEntity>
