<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>EdgeSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>7f5c41aa-09c0-40a1-ac67-415202fb399c</testSuiteGuid>
   <testCaseLink>
      <guid>627bc1cc-95d0-48bf-afe9-e3fa02756f6c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FilesModule/Create_file</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>6f0bf3b1-33b0-409a-8b9d-8bba5aa3663b</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestDataForCreateFile</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>6f0bf3b1-33b0-409a-8b9d-8bba5aa3663b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FileName</value>
         <variableId>fbbf9b51-72f4-495f-9cbf-a8e08f06ebf3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6f0bf3b1-33b0-409a-8b9d-8bba5aa3663b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Desription</value>
         <variableId>02884025-536f-4943-85bd-c1e5dc201c49</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>98cef084-a154-4a49-afb5-ebe99d287b98</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FilesModule/Create_folder</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>69a2a0ab-a643-4150-a0ac-a1bc413bb2ee</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestDataForCreateFolder</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>69a2a0ab-a643-4150-a0ac-a1bc413bb2ee</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FolderName</value>
         <variableId>ee5dd06b-fe53-4cd7-b0ae-9d5aa0e1949d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d839b7d-abd5-48a9-9050-61b7d5242a7c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a517dc0a-c1fd-4d9c-a84c-d580eb748a8f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Obsolate-FM/Rename_File_Old</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43541ba9-e540-49a6-bb6a-d0593c793b53</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffcb9fc3-f4be-4ad0-8e85-396f12d20480</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d834d87-7d20-488b-8b62-dc7053677728</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a2304424-3630-4642-a1ad-346414a69743</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Obsolate-FM/Rename_Folder</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aeb53a0e-86e0-4c0a-b07f-a600d966296b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7387cc82-73d5-4707-9683-6385e40d7781</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2b766af-3fe6-4951-8c7c-f50e8d8e8c45</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>03fde6e5-db8b-4927-94e3-9a931c6439f2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Obsolate-FM/DownloadFile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>991b8001-84ba-41d6-8c98-db7bcd5aaf74</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0b1c8294-55c4-4369-86d2-79621fb7a49f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Obsolate-FM/Delete_file</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af80d949-2488-43e7-98f5-2b18b2570e31</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5824cc93-061b-4f17-822c-60dd52919627</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>afc44a3d-6794-45b8-ae3c-67ad8abc0824</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Obsolate-FM/Delete_folder</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8f16002-bb22-4106-b066-ad8a623656d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53ac70d7-5c50-4333-8424-0e9b5c207b3d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>85a0e728-e4c1-4ec1-8a94-015929a6b24f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Obsolate-JS/JobSubmission-RemoteFile_Edge</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>819ca284-4efb-456b-8cad-be2566161bd5</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestDataForJobSubmission</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>819ca284-4efb-456b-8cad-be2566161bd5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>AppName Element</value>
         <variableId>8726543d-6615-4fa6-8f9f-5d228fd3548c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>819ca284-4efb-456b-8cad-be2566161bd5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>remoteFileName</value>
         <variableId>0b7d0060-243a-4685-9ad1-752817d150e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>819ca284-4efb-456b-8cad-be2566161bd5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FileNameElemnt</value>
         <variableId>5266d8e8-bfe1-4178-bd36-f015a044db8b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a25e19be-4a97-4611-82eb-5151381d5684</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ProfileModule/CreateProfile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d2bae20-a478-4749-8ac6-272295f8a53c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50871651-4438-4afa-a3d1-e015def75e60</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>449134c1-4ff3-4836-9e8f-ac89476b1ec7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>796b0670-b2f1-427e-a522-2cb840506286</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3e8a665b-3dc0-4e3d-8db8-1309dd903104</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e06a756c-3750-4d42-9a5b-69da9cc7d2bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4c0253a-b76c-4b00-b4c9-d3db25c231c4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0357699b-50cc-4648-8e6d-8f984b82e99c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ProfileModule/JobSubmissionThroughProfile-Edge</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>92b2a7df-4982-48ee-be0d-70a6762670f8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ProfileModule/JobSubmissionThroughProfileContextMenu</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>040fb4f4-5c49-4dd6-b866-604e5fdfc063</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d792b765-1aff-44fe-bdbd-48a024d6695c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2a0a489-c108-4daa-8c8b-21fef957092e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f005134-2a3d-4193-9493-cbe7dc342ffd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>824143cc-6f6d-4c82-bee1-7db945b50af3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ProfileModule/DeleteProfile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4343b31b-60fa-4ed8-9029-52a057e6f17f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0300cf62-3068-4779-b99e-ee7267d531f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d45d70d8-f2f8-48b4-94fb-152c1a5ecfc0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a35896b4-0dab-4ed8-9c49-e224d251625a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Obsolate-JS/JobSubmission-RemoteFile_Edge</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8726543d-6615-4fa6-8f9f-5d228fd3548c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b7d0060-243a-4685-9ad1-752817d150e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5266d8e8-bfe1-4178-bd36-f015a044db8b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2f130e70-ee0a-49da-b659-d784f9fdc323</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Obsolate-JM/VerifyInputFiles</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77f8c850-1a37-4580-867f-9a5f05e9cec4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a0c37198-a45e-44be-b1bc-1211a3b3c3d4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Obsolate-JM/VerifyJobDetails</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bdbc0920-41ce-4518-ae3d-dcde8b5cecc5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0b0f6164-0ab6-4dc2-8643-aa6333838da5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Obsolate-JM/VerifyOutputFiles</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c86e2962-3831-4ae0-97c5-b785b07dca8c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>29de86b8-2283-4a0e-9694-f0216d3c47b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Obsolate-JM/ResubmitJob</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7fd3cc8-7705-43fa-a68e-56481aee5747</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
