<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>LoginLogout</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>63a8a387-f9a2-4197-a336-bdd79271096b</testSuiteGuid>
   <testCaseLink>
      <guid>a063b961-7268-4491-9509-026736997712</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Generic/Login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1991935-fee5-4bd6-93ef-69d926d426ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9f306f6-7b79-4ccf-bf72-96287dd25fce</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ea789075-773b-413d-8fbc-ab23079b9082</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Generic/Login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1991935-fee5-4bd6-93ef-69d926d426ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9f306f6-7b79-4ccf-bf72-96287dd25fce</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>54ba90f1-f119-49ac-ad62-db2b344218a8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Generic/Login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1991935-fee5-4bd6-93ef-69d926d426ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9f306f6-7b79-4ccf-bf72-96287dd25fce</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ac5a7c40-9b30-4db0-aa61-9119aba02186</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Generic/Login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1991935-fee5-4bd6-93ef-69d926d426ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9f306f6-7b79-4ccf-bf72-96287dd25fce</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
