<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>New test cases</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>92d9b85e-65bd-4325-80ad-6d6f0dd3b5a6</testSuiteGuid>
   <testCaseLink>
      <guid>bbf4bd8a-0037-401f-97e4-a329cad86cb7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Access_Management/Access_management</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>9e6635d5-7d13-453f-b3e8-a03ac147853d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestDataForAccess_Management</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>9e6635d5-7d13-453f-b3e8-a03ac147853d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value></value>
         <variableId>bebb1369-76cb-4dd7-b801-95005bd8c662</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9e6635d5-7d13-453f-b3e8-a03ac147853d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value></value>
         <variableId>97b65ffa-b5d0-429d-9799-4d154bc186bb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>9e6635d5-7d13-453f-b3e8-a03ac147853d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value></value>
         <variableId>153e9f4e-32e6-47ed-ad96-eb08e4d70bd2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DATA_COLUMN</type>
         <value></value>
         <variableId>f2755deb-09f2-4ef6-a318-116719a31ed7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DATA_COLUMN</type>
         <value></value>
         <variableId>eebf5735-c5bc-4d89-a41b-13abf7812f2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DATA_COLUMN</type>
         <value></value>
         <variableId>6a6999c4-2652-4212-bee1-ea6d888e1150</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8ac20777-948a-4339-841f-33f7c8c9dae7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cluster_Registration/Cluster_Creation</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61bb1931-ff5e-4b54-9cb5-2913910f6c11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92b3b022-d33d-4d49-94ce-6400f4d698a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83c01e78-e3fa-49be-ae95-7e83576cb736</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f00d8bf0-02be-43e1-a239-8de03b0b8464</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55baf40f-4bbe-4599-9d12-a4797252792c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6d11e21-055d-490a-b1e1-504f2fb5f0b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb98ea82-34bc-4398-962d-5472d6b7bdd7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a123b72-e999-4b94-8dd4-493f4528c803</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8cad17c4-2c4b-4488-ab60-a5eabd45ded4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cluster_Registration/Cluster_Edit</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1644a65e-7d84-4197-8c91-fa08a8692551</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40487acb-0e66-49e7-a8e6-c238803bcf44</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3939071-337b-4468-abb2-148c81ebd537</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30348805-67ff-4709-b0be-20d83a738b07</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96df2072-f7d3-405e-b23d-ef0993d4fd7d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02e1ac0c-6198-45b9-bc41-d35eb124ead6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9dbe4533-fee0-490d-b2b5-17ab22a0ffa9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>993aa53f-f958-4c21-92a3-d2989c6aea14</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Generic_Actions/Generic_Actions</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e47b77ef-b2e7-4db0-8e59-d0281e610867</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af386d66-71c7-4cf3-9748-0abd139a3e50</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aa419694-f604-4291-918b-7b9298f0e272</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Preferences/Set_Preferences</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20e66ddf-642f-491a-b46e-0d3dc565bf8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4611fa3d-9817-4318-9699-09323a3d16ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8c467d1f-9c4c-493c-a375-d9145f840bda</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71b6bb43-2854-4a87-80e8-e8a6cc55b8f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a94cf29-3aca-457a-8b05-cbec1a213170</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>003edf9a-5cd2-49e7-b7ef-cf2adf5857a1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>630400d7-1a60-442c-afcd-0566c0a50cbe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80fb4bcc-6ac6-46ae-b1f3-d80a3cca2ee6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
