<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>NewFeature-Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>3fff9a99-531a-4c57-a485-2d6d721aa122</testSuiteGuid>
   <testCaseLink>
      <guid>08cb6b32-193c-4562-8fa8-7b32be074b67</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/FilesModule/BookMark-FilesTab</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b42dc282-7cab-4a76-89c4-3051156f6d6c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d9e28b82-c4e5-4ff0-b42e-654a17e55886</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/FilesModule/UnzipOnUpload</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c7b3a5f8-e7bd-4b89-9a5f-948e44f860e9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e423a0a2-7bba-4954-abbb-c3481b0502a4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/FilesModule/EditFilePath-FilesTab</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>984824c6-5c08-48ae-bc77-5162dfb8fe5e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9c3b3390-a82c-4f30-9655-215ef5baff5a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Obsolate-JS/JobSubmission-RemoteFile-RFB-Output-Folder</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ecd0a139-c46a-4f26-a71c-1d6563db730d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a89c9e8-bea8-407b-af02-819a6c910222</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91ae0513-ffbb-4d4d-9c3c-2d6ff7aa720d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>561222b9-a604-4d74-9d28-b193bf04c8b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2567c18d-af88-4c16-afe6-fe4065bd8e3c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>414d576f-990c-43b8-945b-3ec5e03378b1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-RemoteFile-RFB-ContextMenu</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>08d35b36-96e7-47b9-b569-07442a2ede71</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>13-15</value>
         </iterationEntity>
         <testDataId>Data Files/TestDataForJobSubmission</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>08d35b36-96e7-47b9-b569-07442a2ede71</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>AppName Element</value>
         <variableId>50871651-4438-4afa-a3d1-e015def75e60</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>08d35b36-96e7-47b9-b569-07442a2ede71</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>RemoteFile</value>
         <variableId>fa016057-1646-44eb-aca6-ca256affe5b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>08d35b36-96e7-47b9-b569-07442a2ede71</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Version</value>
         <variableId>66f583dd-0003-4edf-b994-00dbc3b28059</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>08d35b36-96e7-47b9-b569-07442a2ede71</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Desription</value>
         <variableId>449134c1-4ff3-4836-9e8f-ac89476b1ec7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>08d35b36-96e7-47b9-b569-07442a2ede71</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FileArg</value>
         <variableId>c20ffa81-ef5c-405a-b281-7d065b6fbd73</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b0a09134-9bf6-4a9a-8908-6720c48e594d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Obsolate-JS/rfb-switchApplication</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5fc2ade-2b0d-4f8c-9c81-250fff92cae5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6413bb5-8219-4755-a651-79cc0c9b129f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d136fd6a-f3fa-44c6-bfda-d4211751b61f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11230f5d-2647-4379-8eb7-5ddb6672c072</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e50dac30-7a76-48be-b01d-426bbf80bc96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>622ae497-c74e-472f-972d-2996e7120e60</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e075367b-5bbc-4fad-a260-d39aa39060d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-RemoteFile-RFB-ContextMenu</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50871651-4438-4afa-a3d1-e015def75e60</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa016057-1646-44eb-aca6-ca256affe5b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66f583dd-0003-4edf-b994-00dbc3b28059</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>449134c1-4ff3-4836-9e8f-ac89476b1ec7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c20ffa81-ef5c-405a-b281-7d065b6fbd73</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e6e24308-fc16-420e-82ce-6cff26ecf302</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/FilesModule/Pagination-FilesTab</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a01fec8-ead4-4f57-92f3-03c7b5eafee2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0897d5a5-0b32-4d65-8610-6e93cd02a6ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7cb60b7-967b-4fe9-a0d4-ecb89c50d80e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a1e7af26-ed6c-41d7-bdab-01f61e4c2dea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FilesModule/FileOperations - Bookmark</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d935674-32e0-4d9c-a5a2-02a91f2765ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ff2041d-3d7f-420a-873c-e1626bf9061a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20621fd8-78a3-4263-9aec-8e5f976aee20</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>555f7fb9-d8cc-4ef2-9bfe-3a93d5c9060a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
