<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Left-Nav-AppList-ID</name>
   <tag></tag>
   <elementGuidId>0dab3df7-d62c-46c4-8d2b-de5329127f10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[contains(@data-node,'&quot;id&quot;:&quot;Optistruct&quot;')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
