<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PrimaryFile_HiddenFiled</name>
   <tag></tag>
   <elementGuidId>e99e846c-22df-4510-a266-0450bce5447c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'submission_primary_file_field_hidden' and @value = '/stage/david/RunJob.sh']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='submission_primary_file_field_hidden']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submission_primary_file_field_hidden</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>/stage/david/RunJob.sh</value>
   </webElementProperties>
</WebElementEntity>
