<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>polygon</name>
   <tag></tag>
   <elementGuidId>888dccc9-efcf-4fc8-88e9-c1d94e831ff3</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>polygon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>points</name>
      <type>Main</type>
      <value>0,0 0,10 6,5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nav_hpccluster_node&quot;)/ul[@class=&quot;css-jt4bmz&quot;]/li[@class=&quot;css-79elbk&quot;]/div[2]/ul[@class=&quot;css-cpf1ah&quot;]/li[@class=&quot;css-79elbk&quot;]/div[2]/ul[@class=&quot;css-cpf1ah&quot;]/li[@class=&quot;css-79elbk&quot;]/div[@class=&quot;node_clickedtrue
                        decorator-header-container&quot;]/div[@class=&quot;tree-arrow&quot;]/div[1]/svg[1]/polygon[1]</value>
   </webElementProperties>
</WebElementEntity>
